#!/bin/bash
SOURCE=~/unpack
DESTINATION=~/import
COUNTER=0

for FILENAME in $(find "$SOURCE/" -maxdepth 1 -type f); do
    FILESIZE="$(stat -c %s $FILENAME)"
    sleep 2
    if [[ $FILESIZE -eq "$(stat -c %s $FILENAME)" ]]; then
        mv "$FILENAME" "$DESTINATION/" && let COUNTER+=1
    fi
done
if [[ $COUNTER -ne 0 ]]; then
    echo "Moved $COUNTER items"
fi
