#!/bin/bash
 #Removes old revisions of snaps
 #CLOSE ALL SNAPS BEFORE RUNNING THIS
 set -eu
 LANG=en_US.UTF-8 snap list --all | awk '/disabled/{print $1, $3}' |
     while read snapname revision; do
         echo Removing snap "$snapname" with revision "$revision" ...
         sudo snap remove "$snapname" --revision="$revision"
     done

