#!/bin/sh
echo "Filename,FileFormat,GeneralBitRate,Duration,VideoFormat,VideoCodec,Width,Height,VideoBitRate,VideoFrameRate,AudioFormat,AudioCodec,AudioBitRate,AudioSamplingRate,AudioChannels"

find $1 -type f -regex '.*\.\(mp4\|avi\|mkv\)' | while read movie;do
    general=`mediainfo --Inform="General;%Format%,%BitRate%,%Duration%" "$movie"`
    video=`mediainfo --Inform="Video;%Format%,%CodecID%,%Width%,%Height%,%BitRate%,%FrameRate%" "$movie"`
    audio=`mediainfo --Inform="Audio;%Format%,%CodecID%,%BitRate%,%SamplingRate%,%Channels%" "$movie"`
    echo "\"`basename \"$movie\"`\",$general,$video,$audio"
done
